env:
  global:
    - NODE_OPTIONS=--max-old-space-size=8192
matrix:
  include:
  - language: node_js
    env: LANE='node'
    node_js: 8
    cache: yarn
    script:
      - yarn lint
      - yarn test
  - language: android
    env: ANDROID_API_LEVEL=18
    sudo: required
    jdk: openjdk8
    before_cache:
      - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
      - rm -rf $HOME/.gradle/caches/*/plugin-resolution/
    cache:
      directories:
        - "$HOME/.cache/yarn"
        - "$HOME/.gradle/caches/"
        - "$HOME/.gradle/wrapper/"
    android:
      components:
        - tools
        - platform-tools
        - build-tools-28.0.3
        - android-$ANDROID_API_LEVEL
        - extra-google-google_play_services
    before_install:
      - yes | sdkmanager "platforms;android-28"
      - nvm install 8
    before_script:
      - npm install -g yarn
      - yarn config set cache-folder "$HOME/.cache/yarn"
      - yarn install
      - cp google-services.json.dist android/app/google-services.json
    script:
      - cd android && ./gradlew clean && ./gradlew assembleDebug --stacktrace
  # https://medium.com/@fawwazyusran/how-to-travis-ci-working-for-android-api-level-28-2fde7292813c
  - language: android
    env: ANDROID_API_LEVEL=28
    sudo: required
    jdk: openjdk8
    before_cache:
      - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
      - rm -rf $HOME/.gradle/caches/*/plugin-resolution/
    cache:
      directories:
        - "$HOME/.cache/yarn"
        - "$HOME/.gradle/caches/"
        - "$HOME/.gradle/wrapper/"
    android:
      # components:
      #   - tools
      #   - platform-tools
      #   - build-tools-28.0.3
      #   - android-$ANDROID_API_LEVEL
      #   - extra-google-google_play_services
      components:
        - tools
        - platform-tools
        - tools
        - extra-android-m2repository
        - extra-google-google_play_services
      licenses:
        - 'android-sdk-preview-license-52d11cd2'
        - 'android-sdk-license-.+'
        - 'google-gdk-license-.+'
    before_install:
      - touch $HOME/.android/repositories.cfg
      - yes | sdkmanager "platforms;android-28"
      - yes | sdkmanager "build-tools;28.0.3"
      - nvm install 8
    before_script:
      - npm install -g yarn
      - yarn config set cache-folder "$HOME/.cache/yarn"
      - yarn install
      - cp google-services.json.dist android/app/google-services.json
    script:
      - cd android && ./gradlew clean && ./gradlew assembleDebug --stacktrace
  - language: objective-c
    env: LANE='ios'
    os: osx
    osx_image: xcode10.3
    cache:
      cocoapods: true
    podfile: ios/Podfile
    addons:
      homebrew:
        update: false
        taps: wix/brew
        packages:
          - applesimutils
    before_install:
      - nvm install 8
      - npm install -g yarn
    install:
      - yarn global add detox-cli
      - yarn install
      - cd ios/ && pod install --repo-update && cd ..
    before_script:
      - cp GoogleService-Info.plist.dist ios/GoogleService-Info.plist
    script:
      - detox build --configuration ios.sim.release
      - detox test --configuration ios.sim.release --cleanup

notifications:
  email: false
