# https://github.com/natario1/CameraView/blob/master/.github/workflows/build.yml
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions
name: Build
on: [push, pull_request]
jobs:
  IOS_SIMULATOR_TESTS:
    name: iOS Simulator Tests
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: yarn install
      - run: |
          brew tap wix/brew
          brew install applesimutils
      - run: cp GoogleService-Info.plist.dist ios/GoogleService-Info.plist
      - run: cd ios/ && pod install --repo-update && cd ..
      - run: node node_modules/.bin/detox build -c ios.sim.release
        env:
          googleMapsApiKey: ${{ secrets.googleMapsApiKey }}
      # See screenshot specifications
      # https://help.apple.com/app-store-connect/#/devd274dd925
      - name: Run Detox on 6.5 inch device
        run: node node_modules/.bin/detox test -c ios.sim.release --take-screenshots manual --cleanup --device-name="iPhone 11" --artifacts-location ./artifacts/6.5-inch
      - name: Run Detox on 5.5 inch device
        run: node node_modules/.bin/detox test -c ios.sim.release --take-screenshots manual --cleanup --device-name="iPhone 8 Plus" --artifacts-location ./artifacts/5.5-inch
      - name: Run Detox on 12.9 inch device
        run: node node_modules/.bin/detox test -c ios.sim.release --take-screenshots manual --cleanup --device-name="iPad Pro (12.9-inch) (3rd generation)" --artifacts-location ./artifacts/12.9-inch
      - name: Upload screenshots artifacts
        uses: actions/upload-artifact@v1
        with:
          name: detox-screenshots-ios
          path: artifacts
